// app/components/room/AddButton.tsx
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

interface AddButtonProps {
    onClick: () => void;
    className?: string;
}

export const AddButton = ({ onClick, className }: AddButtonProps) => {
    return (
        <Button
            onClick={onClick}
            className={cn(
                className,
                "rounded-full bg-gray-400 hover:bg-gray-500 p-1 aspect-square relative w-8"
            )}>
            <svg className="rounded-full w-full h-full">
                <path stroke="#000" strokeWidth="2" d="M12.5 5v15M5 12.5h15" />
            </svg>
        </Button>
    );
};

// src/components/AddButton.vue
<script setup>

const emits = defineEmits(['click'])
</script>

<template>
  <button
    @click="emits('click')"
    class="rounded-full bg-gray-400 hover:bg-gray-500 p-1 content-center"
  >
    <svg
      width="25"
      height="25"
      class="rounded-full"
    >
      <line
        x1="12.5"
        y1="5"
        x2="12.5"
        y2="20"
        stroke="black"
        stroke-width="2"
      />
      <line
        x1="5"
        y1="12.5"
        x2="20"
        y2="12.5"
        stroke="black"
        stroke-width="2"
      />
    </svg>
  </button>
</template>
