// app/components/CloseButton.tsx
import React from "react";

interface CloseButtonProps {
    className?: string;
    color?: string;
    onClick: () => void;
}

export default function CloseButton({ className, color = "bg-gray-400", onClick }: CloseButtonProps) {
    return (
        <button onClick={onClick} className={className + ` rounded-full hover:bg-gray-500 p-1 ${color}`}>
            <svg width="25" height="25" className="rounded-full">
                <line x1="5" y1="5" x2="20" y2="20" stroke="black" strokeWidth="2" />
                <line x1="20" y1="5" x2="5" y2="20" stroke="black" strokeWidth="2" />
            </svg>
        </button>
    );
}

// src/components/CloseButton.vue
<script setup>

const emits = defineEmits(['click'])
</script>

<template>
  <button
    @click="emits('click')"
    class="rounded-full bg-gray-400 hover:bg-gray-500 p-1"
  >
    <svg
      width="25"
      height="25"
      class="rounded-full"
    >
      <line
        x1="5"
        y1="5"
        x2="20"
        y2="20"
        stroke="black"
        stroke-width="2"
      />
      <line
        x1="20"
        y1="5"
        x2="5"
        y2="20"
        stroke="black"
        stroke-width="2"
      />
    </svg>
  </button>
</template>
